In [1]:
from numpy import *

In [2]:
random.rand(4,4)

array([[0.46841302, 0.20598532, 0.62564686, 0.1706162 ],
       [0.28747037, 0.90498204, 0.89584741, 0.14804534],
       [0.40345352, 0.26054843, 0.45574976, 0.08099517],
       [0.09849574, 0.31265252, 0.35811508, 0.21732438]])

In [3]:
randomMatrix=mat(random.rand(4,4))

In [4]:
randomMatrix

matrix([[0.41795599, 0.06189672, 0.9207353 , 0.59935946],
        [0.36838276, 0.41661719, 0.13505789, 0.18687849],
        [0.37252227, 0.46689536, 0.51062294, 0.94815161],
        [0.92529881, 0.2829425 , 0.36271072, 0.09158242]])

### inverse operation of the matrix  =》 .I

In [6]:
InverseRandomMatrix=randomMatrix.I

In [7]:
InverseRandomMatrix

matrix([[-0.94321692, -2.17118882,  0.82731457,  2.03810766],
        [ 0.6234875 ,  4.78558076, -1.17168671, -1.71516096],
        [ 2.20340975,  2.5292774 , -1.76666946, -1.29098488],
        [-1.12307532, -2.86563488,  2.25803966,  0.73908718]])

In [8]:
randomMatrix*InverseRandomMatrix

matrix([[ 1.00000000e+00, -2.07395057e-16, -1.23935709e-17,
          7.24991334e-17],
        [-3.71444350e-17,  1.00000000e+00,  7.68711604e-17,
          1.69901129e-16],
        [-2.78758491e-17,  2.11497496e-16,  1.00000000e+00,
          2.51739597e-17],
        [ 1.68583188e-16,  3.85980709e-16, -2.14109635e-16,
          1.00000000e+00]])