In [1]:
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm

In [2]:
nsample=20

In [3]:
x=np.linspace(0,10,nsample)

In [4]:
xPlus=np.column_stack((x,x**2))

In [5]:
x

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [6]:
xPlus

array([[  0.        ,   0.        ],
       [  0.52631579,   0.27700831],
       [  1.05263158,   1.10803324],
       [  1.57894737,   2.49307479],
       [  2.10526316,   4.43213296],
       [  2.63157895,   6.92520776],
       [  3.15789474,   9.97229917],
       [  3.68421053,  13.5734072 ],
       [  4.21052632,  17.72853186],
       [  4.73684211,  22.43767313],
       [  5.26315789,  27.70083102],
       [  5.78947368,  33.51800554],
       [  6.31578947,  39.88919668],
       [  6.84210526,  46.81440443],
       [  7.36842105,  54.29362881],
       [  7.89473684,  62.32686981],
       [  8.42105263,  70.91412742],
       [  8.94736842,  80.05540166],
       [  9.47368421,  89.75069252],
       [ 10.        , 100.        ]])

In [13]:
xConstant=sm.add_constant(xPlus)

In [14]:
xConstant

array([[  1.        ,   0.        ,   0.        ],
       [  1.        ,   0.52631579,   0.27700831],
       [  1.        ,   1.05263158,   1.10803324],
       [  1.        ,   1.57894737,   2.49307479],
       [  1.        ,   2.10526316,   4.43213296],
       [  1.        ,   2.63157895,   6.92520776],
       [  1.        ,   3.15789474,   9.97229917],
       [  1.        ,   3.68421053,  13.5734072 ],
       [  1.        ,   4.21052632,  17.72853186],
       [  1.        ,   4.73684211,  22.43767313],
       [  1.        ,   5.26315789,  27.70083102],
       [  1.        ,   5.78947368,  33.51800554],
       [  1.        ,   6.31578947,  39.88919668],
       [  1.        ,   6.84210526,  46.81440443],
       [  1.        ,   7.36842105,  54.29362881],
       [  1.        ,   7.89473684,  62.32686981],
       [  1.        ,   8.42105263,  70.91412742],
       [  1.        ,   8.94736842,  80.05540166],
       [  1.        ,   9.47368421,  89.75069252],
       [  1.        ,  10.     

In [21]:
beta = np.array([5,2,3])

In [22]:
beta

array([5, 2, 3])

In [23]:
e=np.random.normal(size=nsample)

In [24]:
e

array([ 2.20746656,  0.37887935, -0.10649859, -0.58065968,  0.65745894,
        1.09003955, -2.82229594,  2.06055084,  0.47075622,  0.86818045,
        0.10611927,  1.49876238,  0.2057013 , -0.03407496, -0.64131238,
       -0.76653783, -1.86410111, -1.50375205, -0.70692993,  1.01561113])

In [25]:
y=np.dot(xConstant,beta)+e

In [27]:
model=sm.OLS(y,xConstant)

In [28]:
results=model.fit()

In [30]:
results.params

array([5.81143175, 1.83621392, 3.00246026])

In [32]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 6.259e+04
Date:                Thu, 24 Jan 2019   Prob (F-statistic):           1.35e-33
Time:                        17:00:14   Log-Likelihood:                -31.396
No. Observations:                  20   AIC:                             68.79
Df Residuals:                      17   BIC:                             71.78
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.8114      0.768      7.567      0.000       4.191       7.432
x1             1.8362      0.356      5.158      0.000       1.085       2.587
x2             3.0025      0.034     87.370      0.000       2.930       3.075
==============================================================================
Omnibus:                        3.467   Durbin-Watson:                   2.099
Prob(Omnibus):                  0.177   Jarque-Bera (JB):                1.682
Skew:                          -0.635   Prob(JB):                        0.431
Kurtosis:                       3.636   Cond. No.                         137.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""