In [4]:
die <- c(1, "fjdsk")

In [5]:
is.vector(die)

[1] TRUE

In [6]:
length(die)

[1] 2

In [7]:
text <- c("Hello", "World")

In [8]:
length(text)

[1] 2

In [10]:
typeof(text)

[1] "character"

In [11]:
typeof(die)

[1] "character"

In [12]:
die1 <- c(1, 2)

In [14]:
typeof(die1)

[1] "double"

In [15]:
typeof(T)

[1] "logical"

In [16]:
attributes(die)

NULL

In [19]:
dice <- c(1:6)

In [22]:
names(dice) <- c("one", "two", "three", "four", "five", "six")

In [23]:
names(dice[1])

[1] "one"

In [24]:
dice["one"]

one 
  1

In [25]:
diceM <- matrix(dice, nrow = 2)

In [26]:
diceM

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [30]:
arr <- array(c(11:14, 21:24, 31:34), dim = c(2,2,3))

In [31]:
arr

, , 1

     [,1] [,2]
[1,]   11   13
[2,]   12   14

, , 2

     [,1] [,2]
[1,]   21   23
[2,]   22   24

, , 3

     [,1] [,2]
[1,]   31   33
[2,]   32   34

In [32]:
ar <- array(c(11:14, 21:24, 31:34), dim = c(2, 2, 3))

In [33]:
ar

, , 1

     [,1] [,2]
[1,]   11   13
[2,]   12   14

, , 2

     [,1] [,2]
[1,]   21   23
[2,]   22   24

, , 3

     [,1] [,2]
[1,]   31   33
[2,]   32   34

In [34]:
hand1 <- c("ace", "king", "queen", "jack", "ten", "spades", "spades", "spades", "spades", "spades")


In [36]:
handM <- matrix(hand1, nrow = 5)

In [37]:
handM

[,1]  [,2]  
[1,] ace   spades
[2,] king  spades
[3,] queen spades
[4,] jack  spades
[5,] ten   spades

In [38]:
mil <- 10000000

In [39]:
class(mil) <- "POSIXct"

In [40]:
mil

[1] "1970-04-27 01:46:40 CST"

In [41]:
gender <- factor(c("male", "female", "male", "female"))

In [42]:
typeof(gender)

[1] "integer"

In [54]:
levels(gender)

[1] "female" "male"

In [44]:
unclass(gender)

[1] 2 1 2 1
attr(,"levels")
[1] "female" "male"

In [45]:
attr(gender)

ERROR: Error in attr(gender): either 2 or 3 arguments are required


In [55]:
sum(c(TRUE, TRUE, FALSE, FALSE))

[1] 2

In [56]:
as.character(TRUE)

[1] "TRUE"

In [65]:
card <- list("ace", "hearts", list(1, 3, 2))

In [82]:
card[5]

[[1]]
NULL

In [83]:
list1 <- list(100:130, "R", list(TRUE, FALSE))

In [84]:
list1

[[1]]
 [1] 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
[20] 119 120 121 122 123 124 125 126 127 128 129 130

[[2]]
[1] "R"

[[3]]
[[3]][[1]]
[1] TRUE

[[3]][[2]]
[1] FALSE

In [85]:
df <- data.frame(face = c("ace", "two", "six"),
suit = c("clubs", "clubs", "clubs"), value = c(1, 2, 3))

In [86]:
names(df)

[1] "face"  "suit"  "value"

In [87]:
df

face suit  value
1 ace  clubs 1    
2 two  clubs 2    
3 six  clubs 3

In [ ]:
read