In [77]:
import numpy as np

In [48]:
def numpySum(n):
    a=np.arange(n) **2
    b=np.arange(n) **3
    c=a+b
    return c

In [49]:
numpySum(4)

array([ 0,  2, 12, 36])

### array object

In [50]:
a=arange(5)

In [51]:
a.dtype

dtype('int64')

In [52]:
a

array([0, 1, 2, 3, 4])

In [53]:
a.shape

(5,)

### create a multi-dimensional array

In [54]:
m=array([arange(2),arange(2)])

In [55]:
m.shape

(2, 2)

In [56]:
sevenDimensionalArange=arange(7,dtype=uint16)

In [57]:
sevenDimensionalArange

array([0, 1, 2, 3, 4, 5, 6], dtype=uint16)

In [58]:
a.dtype.itemsize

8

In [59]:
sevDimensionFloatArr=arange(7,dtype='f')

In [60]:
sevDimensionFloatArr

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [61]:
a.dtype.itemsize

8

In [62]:
floatArr=arange(7,dtype='f')

In [65]:
floatArr


array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

In [66]:
t=dtype('Float64')

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: Numeric-style type codes are deprecated and will result in an error in the future.
  """Entry point for launching an IPython kernel.


In [67]:
t.char

'd'

In [68]:
t.type

numpy.float64

### Custom dataType

In [71]:
t = dtype([('name', str_, 40), ('numitems', int32), ('price',float32)])

In [72]:
t

dtype([('name', '<U40'), ('numitems', '<i4'), ('price', '<f4')])

In [73]:
t['name']

dtype('<U40')

In [79]:
MyCustomDTypeItems=array([('Meaning of life DVD',42,3.14),
                          ('Butter',25,2.17)],dtype=t)

In [80]:
MyCustomDTypeItems[1]

('Butter', 25, 2.17)

### Index of arr

In [81]:
a=arange(9)

In [82]:
a[3:7]

array([3, 4, 5, 6])

### index by 2 steps

In [84]:
a[:7:2]

array([0, 2, 4, 6])

### reverse index

In [85]:
a[::-1]

array([8, 7, 6, 5, 4, 3, 2, 1, 0])

### multi dimensions by function reshape()

In [91]:
multiDimensions=arange(24).reshape(2,3,4)

In [93]:
multiDimensions.shape

(2, 3, 4)

In [95]:
multiDimensions

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [98]:
multiDimensions[1,2,2]

22

In [99]:
multiDimensions[0,1]

array([4, 5, 6, 7])

In [100]:
multiDimensions[0,:,:]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
multiDimensions[0,1,::2]

array([4, 6])

In [102]:
multiDimensions[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

## change the dimensions of the arr

In [103]:
multiDimensions

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [105]:
multiDimensions.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [106]:
multiDimensions.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [107]:
multiDimensions

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

### change the dimensions by shape()

In [108]:
multiDimensions.shape=(6,4)

In [109]:
multiDimensions

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [110]:
multiDimensions.transpose()

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

### combined arr

In [112]:
combinedArr=arange(9).reshape(3,3)

In [113]:
combinedArr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [114]:
multiCombinedArr=2*combinedArr

In [115]:
multiCombinedArr

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### horizonal combination

In [117]:
hstack((combinedArr,multiCombinedArr))

array([[ 0,  1,  2,  0,  2,  4],
       [ 3,  4,  5,  6,  8, 10],
       [ 6,  7,  8, 12, 14, 16]])

### vertical combination

In [118]:
vstack((combinedArr,multiCombinedArr))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### Deep path combination

In [120]:
dstack((combinedArr,multiCombinedArr))

array([[[ 0,  0],
        [ 1,  2],
        [ 2,  4]],

       [[ 3,  6],
        [ 4,  8],
        [ 5, 10]],

       [[ 6, 12],
        [ 7, 14],
        [ 8, 16]]])

### colum stack

In [121]:
oned=arange(2)

In [123]:
oned

array([0, 1])

In [124]:
twice_oned=2*oned

In [125]:
twice_oned

array([0, 2])

In [128]:
columned_stack=column_stack((oned,twice_oned))

In [135]:
columned_stack

array([[0, 0],
       [1, 2]])

### compare two numpy arrays

In [142]:
verticalStack=hstack((oned,twice_oned))

In [143]:
verticalStack

array([0, 1, 0, 2])

In [144]:
columned_stack==verticalStack

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [151]:
column_stack((combinedArr,multiCombinedArr))==hstack((combinedArr,multiCombinedArr))

array([[ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [152]:
row_stack((combinedArr,multiCombinedArr))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [153]:
row_stack((oned,twice_oned))

array([[0, 1],
       [0, 2]])

### division of the array

In [160]:
splittedArr=a.reshape(3,3)

In [161]:
splittedArr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### horizonal division

In [162]:
hsplit(splittedArr,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

### vertical division

In [163]:
splittedArr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [164]:
vsplit(splittedArr,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

### Deep path division

In [165]:
threeDimensionArr=arange(27).reshape(3,3,3)

In [166]:
threeDimensionArr

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [167]:
dsplit(threeDimensionArr,3)

[array([[[ 0],
         [ 3],
         [ 6]],
 
        [[ 9],
         [12],
         [15]],
 
        [[18],
         [21],
         [24]]]), array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]), array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]])]

### attribute of the arr

In [170]:
attrTestArr=arange(24)

In [171]:
attrTestArr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [172]:
attrTestArr.size

24

### storage of arr element

In [173]:
attrTestArr.itemsize

8

### storage of the whole element，equals the multi of the itemsize and the size

In [174]:
attrTestArr.nbytes

192

In [175]:
attrTestArr.resize(6,4)

In [176]:
attrTestArr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Transposition

In [177]:
attrTestArr.T

array([[ 0,  4,  8, 12, 16, 20],
       [ 1,  5,  9, 13, 17, 21],
       [ 2,  6, 10, 14, 18, 22],
       [ 3,  7, 11, 15, 19, 23]])

In [179]:
complexNumArr=array([1.j+1,2.j+3])

### real part of complex num

In [180]:
complexNumArr

array([1.+1.j, 3.+2.j])

In [181]:
complexNumArr.real

array([1., 3.])

### imaginary part of complex num

In [183]:
complexNumArr.imag

array([1., 2.])

### iter obj ---> flatiter

In [184]:
f=attrTestArr.flat

In [185]:
for item in f:
    print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [186]:
attrTestArr.flat[2]

2

### trans the numpy arr to the python list

In [187]:
complexNumArr.tolist()

[(1+1j), (3+2j)]

In [188]:
complexNumArr

array([1.+1.j, 3.+2.j])

### change the dataType of the numpy arr

In [189]:
complexNumArr.astype(int)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  """Entry point for launching an IPython kernel.


array([1, 3])

# 4 Summarizing

In [ ]:
h,l,c=np.load