## Basic Counting

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a=tf.constant(2)

In [3]:
b=tf.constant(3)

In [4]:
addOp=tf.add(a,b)

In [5]:
with tf.Session() as sess:
    print(sess.run(addOp))

5


In [6]:
multiOp=tf.multiply(a,b)

In [7]:
powOp=tf.pow(addOp,multiOp)

In [8]:
with tf.Session() as sess:
    writer=tf.summary.FileWriter('./graphs/const_add',sess.graph)
    resultOp=sess.run(powOp)
writer.close()

In [9]:
resultOp

15625

## Basic structure

In [10]:
matrix=np.zeros((3,4))

In [11]:
matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
matrix_by_tf=tf.zeros((3,4))

In [13]:
matrix_by_tf

<tf.Tensor 'zeros:0' shape=(3, 4) dtype=float32>

In [14]:
reshapeMatByTf=tf.reshape(matrix_by_tf,(2,6))

In [15]:
reshapeMatByTf

<tf.Tensor 'Reshape:0' shape=(2, 6) dtype=float32>

## further counting

In [16]:
a=tf.constant([2,2],name='a')

In [17]:
b=tf.constant([[0,1],[2,3]],name='b')

In [18]:
x=tf.multiply(a,b,name='dot_product')

In [19]:
with tf.Session() as sess:
    writer=tf.summary.FileWriter('./graphs/const_mul',sess.graph)
    resultDotProduct=sess.run(x)

In [20]:
writer.close()

In [21]:
resultDotProduct

array([[0, 2],
       [4, 6]], dtype=int32)

## various constant

In [22]:
c=tf.constant([[2,3],[1,4]],name='c')

In [23]:
y=tf.matmul(b,c,name='matrix_mul')

In [24]:
with tf.Session() as sess:
    writer=tf.summary.FileWriter('./graphs/matrix_mul',sess.graph)
    resultMatrixProduct=sess.run(y)

In [25]:
writer.close()

In [26]:
resultMatrixProduct
    

array([[ 1,  4],
       [ 7, 18]], dtype=int32)

In [28]:
allZero=tf.zeros([2,3],tf.int32)

In [29]:
allZero

<tf.Tensor 'zeros_1:0' shape=(2, 3) dtype=int32>

In [30]:
allZeroLike=tf.zeros_like(x,optimize=True)

In [31]:
allZeroLike

<tf.Tensor 'zeros_like:0' shape=(2, 2) dtype=int32>

## various variables

In [32]:
va=tf.Variable(2,name="scalar")

In [33]:
vb=tf.Variable([2,3],name="vector")

In [34]:
vc=tf.Variable([[0,1],[2,3]],name="matrix")

In [35]:
vw=tf.Variable(tf.zeros([23,2]))

In [36]:
va.initializer

<tf.Operation 'scalar/Assign' type=Assign>

In [37]:
va

<tf.Variable 'scalar:0' shape=() dtype=int32_ref>

In [38]:
va.value()

<tf.Tensor 'scalar/read:0' shape=() dtype=int32>

In [39]:
with tf.Session() as sess:
    sess.run(va.initializer)

In [40]:
va.value()

<tf.Tensor 'scalar/read:0' shape=() dtype=int32>