In [12]:
z = array(1:1500)

In [13]:
dim(z) <- c(3, 5, 100)

In [14]:
z(2, 5, 99)

ERROR: Error in z(2, 5, 99): could not find function "z"


In [15]:
z[2, , 99]

[1] 1472 1475 1478 1481 1484

In [19]:
die <- c(1:9)

In [20]:
m <- matrix(die, nrow = 3)

In [21]:
m

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [22]:
ev <- eigen(m)

In [23]:
ev

eigen() decomposition
$values
[1]  1.611684e+01 -1.116844e+00 -5.700691e-16

$vectors
           [,1]       [,2]       [,3]
[1,] -0.4645473 -0.8829060  0.4082483
[2,] -0.5707955 -0.2395204 -0.8164966
[3,] -0.6770438  0.4038651  0.4082483


In [24]:
svd(m)

$d
[1] 1.684810e+01 1.068370e+00 5.543107e-16

$u
           [,1]        [,2]       [,3]
[1,] -0.4796712  0.77669099  0.4082483
[2,] -0.5723678  0.07568647 -0.8164966
[3,] -0.6650644 -0.62531805  0.4082483

$v
           [,1]       [,2]       [,3]
[1,] -0.2148372 -0.8872307  0.4082483
[2,] -0.5205874 -0.2496440 -0.8164966
[3,] -0.8263375  0.3879428  0.4082483

In [25]:
prod(svd(m)$d)

[1] 9.977593e-15