In [1]:
import numpy as np

In [2]:
ar=np.array([1,2,3,4,5,6,7])

In [3]:
print(ar)

[1 2 3 4 5 6 7]


In [4]:
print(ar.ndim)

1


In [5]:
print(ar.shape)

(7,)


In [6]:
print(ar.size)

7


In [7]:
print(ar.dtype)

int64


In [8]:
print(ar.itemsize)

8


In [10]:
print(ar.data)

In [11]:
twoShapeArr=np.array([[1,2,3],[4,5,6]])

In [12]:
print(twoShapeArr.shape)

(2, 3)


In [13]:
print(twoShapeArr.size)

6


## arange

In [14]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [15]:
print(np.arange(10.0))

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [16]:
print(np.arange(5,12))

[ 5  6  7  8  9 10 11]


In [17]:
print(np.arange(5.0,12,2))

[ 5.  7.  9. 11.]


In [18]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]


## linspace

In [19]:
linSOne=np.linspace(2.0,3.0,num=5)

In [20]:
linSOne

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [24]:
linSTwo=np.linspace(2.0,3.0,num=5,endpoint=False)

In [25]:
linSTwo

array([2. , 2.2, 2.4, 2.6, 2.8])

In [26]:
linSThree=np.linspace(2.0,3.0,num=5)

In [27]:
linSThree

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

### show the num of step ---- retstep

In [28]:
linSFour=np.linspace(2.0,3.0,num=5,retstep=True)

In [29]:
linSFour

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [31]:
zeroArr=np.zeros(5)

In [32]:
zeroArr

array([0., 0., 0., 0., 0.])

## zero matrix

In [33]:
np.zeros((3,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

## unit matrix

In [35]:
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
