In [1]:
import numpy as np

In [2]:
TransArr=np.arange(10)

In [3]:
TransArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
print(TransArr,'\n',TransArr.reshape(2,5).T)

[0 1 2 3 4 5 6 7 8 9] 
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [5]:
TransArrTwo=np.ones((2,3,4))

In [6]:
TransArrThree=TransArrTwo.T

In [7]:
print(TransArrTwo.shape)

(2, 3, 4)


In [8]:
print(TransArrThree.shape)

(4, 3, 2)


In [9]:
resizeArr=np.resize(np.arange(5),(3,4))

In [10]:
print(resizeArr)

[[0 1 2 3]
 [4 0 1 2]
 [3 4 0 1]]


## Type trans

In [11]:
ar1=np.arange(10,dtype=float)

In [12]:
print(ar1,ar1.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


In [13]:
ar2=ar1.astype(np.int32)

In [14]:
print(ar2,ar2.dtype)

[0 1 2 3 4 5 6 7 8 9] int32


In [15]:
print(ar1,ar1.dtype)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64


## matrix heap  up

In [16]:
a=np.arange(5)

In [17]:
b=np.arange(5,9)

In [18]:
a,b

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8]))

In [19]:
hArr=np.hstack((a,b))

In [20]:
hArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
print(a,a.shape)

[0 1 2 3 4] (5,)


In [22]:
print(b,b.shape)

[5 6 7 8] (4,)


In [23]:
print(hArr,hArr.shape)

[0 1 2 3 4 5 6 7 8] (9,)


In [24]:
c=np.arange(5)

In [25]:
d=np.arange(5,10)

In [26]:
d

array([5, 6, 7, 8, 9])

In [27]:
vArr=np.vstack((c,d))

In [28]:
vArr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
e=np.arange(16).reshape(4,4)

In [30]:
f=np.hsplit(e,2)

In [31]:
e

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
f

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]), array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [33]:
print(f,type(f))

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])] <class 'list'>


## matrix Splitter

In [34]:
vSpliterArr=np.vsplit(e,4)

In [35]:
vSpliterArr

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [36]:
g=np.array([[1],[2],[3]])

In [37]:
g

array([[1],
       [2],
       [3]])

In [38]:
h=np.array([['a'],['b'],['c']])

In [39]:
h

array([['a'],
       ['b'],
       ['c']], dtype='<U1')

In [40]:
hArrTwo=np.hstack((g,h))

In [41]:
hArrTwo

array([['1', 'a'],
       ['2', 'b'],
       ['3', 'c']], dtype='<U21')

In [42]:
print(g,g.shape)

[[1]
 [2]
 [3]] (3, 1)


In [43]:
print(h,h.shape)

[['a']
 ['b']
 ['c']] (3, 1)


## heap up by the argument of "axis"

In [44]:
i=np.stack((c,d))

In [45]:
i

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [46]:
h=np.stack((c,d),axis=1)

In [47]:
h

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [48]:
print(i,i.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)


In [49]:
print(h,h.shape)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] (5, 2)


## simple operation of arr

In [50]:
operationArr=np.arange(6).reshape(2,3)

In [51]:
print(operationArr)

[[0 1 2]
 [3 4 5]]


In [52]:
print(operationArr+2)

[[2 3 4]
 [5 6 7]]


In [53]:
print(operationArr*2)

[[ 0  2  4]
 [ 6  8 10]]


In [54]:
print(operationArr**0.5)

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]]


In [55]:
print(operationArr.mean())

2.5


In [56]:
print(operationArr.max())

5


In [57]:
print(operationArr.min())

0


In [58]:
print(operationArr.std())

1.707825127659933


In [59]:
print(operationArr.var())

2.9166666666666665


In [61]:
print(operationArr.sum(),np.sum(operationArr,axis=0))

15 [3 5 7]
