In [1]:
import numpy as np
import pandas as pd 
import datetime 
from pandas_datareader import data,wb
import sympy

In [2]:
from scipy.optimize import minimize

In [3]:
x=np.array([4,432,21],int)

In [4]:
print(x)

[  4 432  21]


In [5]:
x2d=np.array(((100,200,300),(111,222,333),(123,456,789)))

In [6]:
x2d

array([[100, 200, 300],
       [111, 222, 333],
       [123, 456, 789]])

In [7]:
x=np.array([4,5,6])

In [8]:
y=np.array([1,2,3])

In [9]:
print(x+y)

[5 7 9]


In [10]:
print(x*y)

[ 4 10 18]


In [11]:
print(x-y)

[3 3 3]


In [12]:
print(x/y)

[4.  2.5 2. ]


In [13]:
print(x%y)

[0 1 0]


In [14]:
mx1=np.matrix(((1,2,3),(1,2,3),(1,2,3)))

In [15]:
mx2=np.matrix(((1,2,3),(1,2,3),(1,2,3)))

In [16]:
mx1

matrix([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

In [17]:
print(mx1*mx2)

[[ 6 12 18]
 [ 6 12 18]
 [ 6 12 18]]


In [18]:
x=np.random.randn(10)

In [19]:
x

array([-1.28696339, -0.85980983,  0.23594904,  0.54558895, -0.63675549,
        1.31605249,  0.81503937,  0.53004015, -1.31266607,  0.23847401])

In [20]:
mean=x.mean()

In [21]:
mean

-0.0415050760175094

In [22]:
std=x.std()

In [23]:
std

0.8714531408160286

In [24]:
type(x)

numpy.ndarray

### Scipy

In [25]:
import scipy as sp

In [26]:
import scipy.stats as st

In [27]:
s=sp.randn(10)

In [28]:
s

array([-1.96990828,  0.80818606, -1.69182016,  0.86671391, -1.29299867,
       -1.68441516,  0.35415516, -0.64653858, -0.45495087, -0.82846383])

In [29]:
n,min_max,mean,var,skew,kurt=st.describe(s)

In [30]:
print("Number of elements: {0:d}".format(n)) 
print("Minimum: {0:3.5f} Maximum: {1:2.5f}".format(min_max[0],min_max[1])) 
print("Mean: {0:3.5f}".format(mean)) 
print("Variance: {0:3.5f}".format(var)) 
print("Skewness : {0:3.5f}".format(skew)) 
print("Kurtosis: {0:3.5f}".format(kurt))

Number of elements: 10
Minimum: -1.96991 Maximum: 0.86671
Mean: -0.65400
Variance: 1.09065
Skewness : 0.30014
Kurtosis: -1.29713


In [31]:
def rosenbrock(x):     
    return sum(100.0*(x[1:]-x[:-1]**2.0)**2.0 + (1-x[:-1])**2.0)  

x0 = np.array([1, 0.7, 0.8, 2.9, 1.1]) 
res = minimize(rosenbrock, x0, method = 'nelder-mead', options =         
               {'xtol': 1e-8, 'disp': True})  
print(res.x)

Optimization terminated successfully.
         Current function value: 0.000000
         Iterations: 516
         Function evaluations: 827
[1. 1. 1. 1. 1.]


### SymPy

In [32]:
a = sympy.Symbol('a')

In [33]:
b = sympy.Symbol('b')

In [34]:
c = sympy.Symbol("c")

In [35]:
e = (a*b*b+2*b*a*b)+(a*a+c*c)

In [36]:
print(e)

a**2 + 3*a*b**2 + c**2


In [37]:
print(e.expand)

<bound method Expr.expand of a**2 + 3*a*b**2 + c**2>
