In [1]:
import numpy as np
import numpy.ma as ma
from numpy import linalg as LA

In [2]:
x2d = np.array( ( (100,200,300), 
                (111,222,333),                   
                (123,456,789) ) )

In [3]:
x2d.shape

(3, 3)

In [4]:
x2d.dtype

dtype('int64')

In [5]:
x2d.size

9

In [6]:
x2d.itemsize

8

In [7]:
x2d.ndim

2

In [8]:
x2d.data

In [9]:
x2d = np.array(( (100,200,300),
                (111,222,333),
                (123,456,789),
                (125,457,791), 
                (127,459,793),                  
                (129,461,795) ))

In [10]:
x2d[0:4,1:3]

array([[200, 300],
       [222, 333],
       [456, 789],
       [457, 791]])

In [11]:
for row in x2d:
    print(row)

[100 200 300]
[111 222 333]
[123 456 789]
[125 457 791]
[127 459 793]
[129 461 795]


In [12]:
x2d.ravel()

array([100, 200, 300, 111, 222, 333, 123, 456, 789, 125, 457, 791, 127,
       459, 793, 129, 461, 795])

In [13]:
x2d

array([[100, 200, 300],
       [111, 222, 333],
       [123, 456, 789],
       [125, 457, 791],
       [127, 459, 793],
       [129, 461, 795]])

In [14]:
x2d.resize((3,6))

In [15]:
x2d

array([[100, 200, 300, 111, 222, 333],
       [123, 456, 789, 125, 457, 791],
       [127, 459, 793, 129, 461, 795]])

In [16]:
x2d.reshape(6,3)

array([[100, 200, 300],
       [111, 222, 333],
       [123, 456, 789],
       [125, 457, 791],
       [127, 459, 793],
       [129, 461, 795]])

In [17]:
x2d.shape=(9,2)

In [18]:
x2d

array([[100, 200],
       [300, 111],
       [222, 333],
       [123, 456],
       [789, 125],
       [457, 791],
       [127, 459],
       [793, 129],
       [461, 795]])

### subClass matrix

In [19]:
a = np.matrix('1 2 3; 4 5 6; 7 8 9')

In [20]:
b = np.matrix('4 5 6; 7 8 9; 10 11 12')

In [21]:
print(a*b)

[[ 48  54  60]
 [111 126 141]
 [174 198 222]]


In [22]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])

In [23]:
x

array([  72,   79,   85,   90,  150, -135,  120,  -10,   60,  100])

### mask array

In [24]:
mx = ma.masked_array(x,mask=[0,0,0,0,0,1,0,1,0,0])

In [25]:
mx_second=ma.masked_array(x,mask=x<0)

In [26]:
mx_third=ma.masked_array(x,mask=x>0)

In [27]:
mx

masked_array(data=[72, 79, 85, 90, 150, --, 120, --, 60, 100],
             mask=[False, False, False, False, False,  True, False,  True,
                   False, False],
       fill_value=999999)

In [28]:
mx_second

masked_array(data=[72, 79, 85, 90, 150, --, 120, --, 60, 100],
             mask=[False, False, False, False, False,  True, False,  True,
                   False, False],
       fill_value=999999)

In [29]:
mx_third

masked_array(data=[--, --, --, --, --, -135, --, -10, --, --],
             mask=[ True,  True,  True,  True,  True, False,  True, False,
                    True,  True],
       fill_value=999999)

In [30]:
x.mean()

61.1

In [31]:
mx.mean()

94.5

In [32]:
mx_second.mean()

94.5

In [33]:
mx_third.mean()

-72.5

### structured array

In [34]:
rectype= np.dtype({'names':['mintemp', 'maxtemp', 'avgtemp', 'city'], 
                  'formats':['i4','i4', 'f4', 'a30']})

In [35]:
a = np.array([(10, 44, 25.2, 'Indore'),
              (10, 42, 25.2, 'Mumbai'), 
              (2,48, 30, 'Delhi')],
             dtype=rectype)

In [36]:
print(a)

[(10, 44, 25.2, b'Indore') (10, 42, 25.2, b'Mumbai')
 ( 2, 48, 30. , b'Delhi')]


In [37]:
print(a["mintemp"])

[10 10  2]


In [38]:
print(a["city"])

[b'Indore' b'Mumbai' b'Delhi']


In [39]:
print(a[2])

(2, 48, 30., b'Delhi')


In [40]:
print(a[0])

(10, 44, 25.2, b'Indore')


### common func

In [41]:
x1 = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100]) 
x2 = np.array([72, 79, 85, 91, 150, -135, 120, -10, 60, 100]) 
x_angle = np.array([30, 60, 90, 120, 150, 180]) 
x_sqr = np.array([9, 16, 25, 225, 400, 625]) 
x_bit = np.array([2, 4, 8, 16, 32, 64])

In [42]:
np.greater_equal(x1,x2)

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [43]:
np.mod(x1,x2)

array([ 0,  0,  0, 90,  0,  0,  0,  0,  0,  0])

In [44]:
np.exp(x1)

array([1.85867175e+31, 2.03828107e+34, 8.22301271e+36, 1.22040329e+39,
       1.39370958e+65, 2.34555134e-59, 1.30418088e+52, 4.53999298e-05,
       1.14200739e+26, 2.68811714e+43])

In [45]:
np.reciprocal(x1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [46]:
np.negative(x1)

array([ -72,  -79,  -85,  -90, -150,  135, -120,   10,  -60, -100])

In [47]:
np.isreal(x1)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [48]:
np.square(x_sqr)

array([    81,    256,    625,  50625, 160000, 390625])

In [49]:
x_sqr

array([  9,  16,  25, 225, 400, 625])

In [50]:
np.sqrt(np.square(x_sqr))

array([  9.,  16.,  25., 225., 400., 625.])

In [51]:
np.sin(x_angle*np.pi/180)

array([5.00000000e-01, 8.66025404e-01, 1.00000000e+00, 8.66025404e-01,
       5.00000000e-01, 1.22464680e-16])

In [52]:
np.left_shift(x_bit,1)

array([  4,   8,  16,  32,  64, 128])

In [53]:
np.right_shift(x_bit,1)

array([ 1,  2,  4,  8, 16, 32])

### math module

In [54]:
arr2d = np.array(( (100,200,300),
                  (111,222,333),                 
                  (129,461,795) ))

In [55]:
eig_val,eig_vec=LA.eig(arr2d)

In [56]:
eig_val

array([1.05664180e+03, 6.03582029e+01, 2.37768608e-14])

In [57]:
eig_vec

array([[ 0.34860455,  0.57805139,  0.41356846],
       [ 0.38695105,  0.64163704, -0.81514943],
       [ 0.8536649 , -0.50414135,  0.4055768 ]])